tests
testMimeEncodeDecodeMultiLine

	| encoded |
	encoded := (self classToBeTested mimeEncode: (String new: 100 withAll: $a) readStream) contents.
	self assert: encoded = 
'YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh
YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYQ=='.
	
	encoded := (self classToBeTested mimeEncode: (String new: 100 withAll: $a) readStream multiLine: false) contents.
	self assert: encoded = 
'YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYQ=='.